// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 001_chirpy.sql

package database

import (
	"context"
	"database/sql"
)

const createChirpy = `-- name: CreateChirpy :one
INSERT INTO chirpies (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid (),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpyParams struct {
	Body   sql.NullString
	UserID sql.NullString
}

func (q *Queries) CreateChirpy(ctx context.Context, arg CreateChirpyParams) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, createChirpy, arg.Body, arg.UserID)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteAllChirpies = `-- name: DeleteAllChirpies :exec
DELETE FROM chirpies
`

func (q *Queries) DeleteAllChirpies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChirpies)
	return err
}
