// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 001_chirpy.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChirpy = `-- name: CreateChirpy :one
INSERT INTO chirpies (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid (),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpyParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirpy(ctx context.Context, arg CreateChirpyParams) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, createChirpy, arg.Body, arg.UserID)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteAllChirpies = `-- name: DeleteAllChirpies :exec
DELETE FROM chirpies
`

func (q *Queries) DeleteAllChirpies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChirpies)
	return err
}

const getChirpyByID = `-- name: GetChirpyByID :one
SELECT id, created_at, updated_at, body, user_id
FROM chirpies
WHERE id = $1
`

func (q *Queries) GetChirpyByID(ctx context.Context, id uuid.UUID) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, getChirpyByID, id)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const listChirpies = `-- name: ListChirpies :many
SELECT id, created_at, updated_at, body, user_id 
FROM chirpies
ORDER BY created_at ASC
`

func (q *Queries) ListChirpies(ctx context.Context) ([]Chirpy, error) {
	rows, err := q.db.QueryContext(ctx, listChirpies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirpy
	for rows.Next() {
		var i Chirpy
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
