// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Chirpy struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Body      sql.NullString
	UserID    sql.NullString
}

type User struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Email     sql.NullString
}
