// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type User struct {
	ID        sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Email     sql.NullString
}
